name: Build Storybook

on: [push, pull_request]

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: |
          yarn
      - name: Build Storybook
        run: |
          yarn build-storybook
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: storybook-files
          path: storybook-static

  deploy-storybook:
    runs-on: ubuntu-latest
    needs: build-storybook
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: storybook-files
          path: storybook-static
      - name: Commit updates
        run: |
          mkdir -p storybook
          rm -rf storybook/${GITHUB_REF##*/}
          mv storybook-static storybook/${GITHUB_REF##*/}
          git add .
          git status
          git diff --cached --quiet && echo 'No changes. Exiting!' && exit 0
          git commit -m "Deploy storybook for ${GITHUB_REF##*/}."
          git pull --no-edit --quiet
          git push origin gh-pages
        env:
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
  
  comment-storybook-url:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: 438
          body: |
            Storybook preview: https://quran.github.io/quran.com-frontend-next/storybook/{{ github.ref }}/
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
